settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: requestbin
  path: .
  commands:
    generate:
        status: true
    run:
        status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
